### ISSUE TITLE
Not Exporting Data on file

### ISSUE THREAD

**Issue by EhsanFox** [bradzacher/mysqldump#108]
I tried exporting the data into a file with my code, but the file only has the default texts (no data)

MyCode: 
`mysqldump({
      connection: {
        host: process.env.DB_IP,
        user: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: "gamezone_3tar",
      },
      dumpToFile: './botData/3TarDB.sql',
  });`

**Comment by dschuessler** [comment]
I can confirm that the data is missing from my dump. Only the schemas are exported.

This is my API call:

```
mysqldump({
    connection: {
      host,
      user,
      database,
      password,
    },
    dumpToFile: filePath,
  });
```

MySQL 5.7
node 10.15

**Comment by dschuessler** [comment]
I resolved my problem by awaiting the call to `mysqldump`.

I deleted data directly after the dump and as I did not await the promise returned by `mysqldump` the deletion finished before the dump, leading to data missing from it.

From the first examples under "Usage" I could not infer that the method was in fact asynchronous rather than synchronous. That threw me off.

**Comment by EhsanFox** [comment]
can u send me the code?

**Comment by dschuessler** [comment]
I just wrote `await mysqldump` in place of `mysqldump`. The rest is the same.

**Comment by EhsanFox** [comment]
with dumpToFile option?

**Comment by dschuessler** [comment]
Yes, I use the `dumpToFile` option.
