### ISSUE TITLE
Feature - Dump Progress Callback

### ISSUE THREAD

**Issue by JoshuaHintze** [bradzacher/mysqldump#109]
It would be great if there was an option you could pass in that would call a callback function to indicate progress.

I am currently running mysqldump in a cron task but if the tasks takes too long it will fail. I can extend the lock time but it would be great to continually call a keepLock() function during a progress update of some sort.

I thought of a couple work arounds. I could not await the promise returned from the dump and create some sort of setInterval that would watch the file being created and see that it continues to grow, however having something inside the library would be great.

Thanks

**Comment by bradzacher** [comment]
Couldn't you just start the dump as well as starting a setInterval, and then clear the interval once the promise resolves?

It'd achieve the exact same result without any changes to the library.

Otherwise we'd have to find a logical place within the library to call a callback. Depending where that is, it could be an inconsistent duration between callbacks depending on the size of the tables being processed.

Doing this in user land would be much more consistent.

**Comment by JoshuaHintze** [comment]
Yeah that was my proposed alternative if I had to figure it out without any changes to mysqldump.

It would just be nice if there was a way internal to the library that I got an everything is progressing just fine. Some of my larger database dumps take about 65 minutes or so.
