### ISSUE TITLE
[Wanted] Maintainers

### ISSUE THREAD

**Issue by webcaetano** [bradzacher/mysqldump#34]
Hey folks,

I am looking for maintainers to help triage issues and merge pull requests for this repository 💯

I'm very happy this library, but unfortunately I just don't have time to maintain it right now like it should. 
Also to help it grow is better to have multiple maintainers.

If you're interested in becoming a maintainer, please leave a comment below and let me know. I would really appreciate the help!

**Comment by Dafrok** [comment]
I'm sorry for such too late I saw this message. Because of the pr https://github.com/webcaetano/mysqldump/pull/36 had been pending period of time and I really need that featrue, I copied and rewrite it with ES Next and republished. This is my version https://github.com/Dafrok/mysql-backup/blob/master/index.js
I would like to transfer the repo if needed.

**Comment by webcaetano** [comment]
@Dafrok it's cool too. Whatever works.
FYI, You don't need to create a package, or wait a PR to be approved to start using it on your project. 
You can call it from `package.json` from a github `repo`, `branch` `tag` or `commit`
I do this all the time.

#### docs
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

Example of calling a package from github from a commit hash
```
"dependencies":{
  "phaser-craft": "git://github.com/webcaetano/craft.git#ff0dbac2224df64cb04d46869002ee77ced12d4f"
}
```
