### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined V 2.2.1

### ISSUE THREAD

**Issue by awaismehmood88** [bradzacher/mysqldump#51]
V 1.4 was working very fine
But new Update doesn't work throw error on MAC but working on LINUX

> TypeError: Cannot read property 'replace' of undefined
>     at tablesRes.map.r (/Users/apple/Documents/Webstorm Projects/psa-prd2-admin/node_modules/mysqldump/dist/cjs.js:53:36)
>     at Array.map (<anonymous>)
>     at /Users/apple/Documents/Webstorm Projects/psa-prd2-admin/node_modules/mysqldump/dist/cjs.js:52:40
>     at Generator.next (<anonymous>)
>     at fulfilled (/Users/apple/Documents/Webstorm Projects/psa-prd2-admin/node_modules/mysqldump/dist/cjs.js:40:58)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>

My code

 

> await mysqlDump({
>                 connection: {
>                     host: 'localhost',//appConfig.DB['HOST'],
>                     user: 'root',//appConfig.DB['USER'],
>                     password: 'root',//appConfig.DB['PASS'],
>                     database: 'Name_DB',//appConfig.DB['DATABASE'],
>                 },
>                 table: {
>                     ifNotExist: true,
>                 },
>                 dumpToFile: appConfig['FILES_BASE_PATH'] + 'backups/backup_' + Date.now() + '.sql'
>             })

**Comment by bradzacher** [comment]
Need some more information in order to solve this!
Node version?
Package version?
DB information?

**Comment by xlxAciDxlx** [comment]
At least in my case (on the latest package version and MySQL), this occurred if you give the options a non-lowercased database name.

Doesn't work:
```js
mysqldump({
	connection: {
		→ database: config.database, ←
		host: config.host,
		password: config.password,
		user: config.username
	},
	dumpToFile: backupFile
});
```

Does work:
```js
mysqldump({
	connection: {
		→ database: config.database.toLowerCase(), ←
		host: config.host,
		password: config.password,
		user: config.username
	},
	dumpToFile: backupFile
});
```

---

I'm assuming in my case, it's because even _if_ the database can be translated by MySQL from `ProjectName` to `projectname`, the results for tables in that database are returned as `Tables_In_projectname` not `Tables_In_ProjectName` (as specified by the first database option). And since you directly pass in the `Tables_In_{dbName}` option, if it expects it to be lowercase it'll error with the mentioned error. Not sure this is really a case you should handle, but a note about case sensitivity somewhere would be helpful. :)

**Comment by adamtaylor13** [comment]
Interesting.. For me this appears to _only_ occur for localhost DBs.
