### ISSUE TITLE
Dump to a string

### ISSUE THREAD

**Issue by chiawendt** [bradzacher/mysqldump#64]
There seems to be no api to get a string output. The easier alternative seems to be using `{dumpToFile: "/tmp/dump.sql"}`, and then read the file.

**Comment by Dafrok** [comment]
how about this fork?

https://github.com/Dafrok/mysql-backup

**Comment by bradzacher** [comment]
There is no way to directly get a dump to a single string, no.
If you don't provide a file path to dump to, then it will return the values from the function:
https://github.com/bradzacher/mysqldump/blob/develop/dist/mysqldump.d.ts#L283-L305

However this is not recommended, because if your DB is too big, you can easily OOM during the dump process, and not be able to get anything.
The best option is to dump the file and read it back.
