### ISSUE TITLE
any ways to backup stored procedures?

### ISSUE THREAD

**Issue by ksairi** [bradzacher/mysqldump#82]

**Comment by LeopoldBriand** [comment]
Is anyone working on this? Is the repo still maintained ?

**Comment by bradzacher** [comment]
This is a problem space very, very few people care about. So contributions are very few.

I still own and maintain this repo, but my **free**, **_unpaid_**, _volunteer_ open source time is dominated by other projects.
As such, by-and-large, this project is maintenance mode - it works for all defined usecases, it isn't broken. If there are security issues or bugs I'll fix them; but I am not actively adding features myself.

You're welcome to submit a PR for if this is important to you. Otherwise it'll likely sit open until someone else is motivated to contribute to it.

**Comment by LeopoldBriand** [comment]
Hello, I didn't mean to reproach you in any way, it's already great to contribute to open source as you do. I will look into it and open a PR. Thanks
