### ISSUE TITLE
How can I remove the \n in the rows ? 

### ISSUE THREAD

**Issue by sostenesapollo** [bradzacher/mysqldump#97]
I think that my backup size is so bigger because of the \n 's 

I need to create a fork, and modify something, or you have a special param in the function invocation ?

**Comment by bradzacher** [comment]
There isn't an option. Happy to accept a PR to add one.

I doubt you'll save that many bytes by removing newlines.
Even if you remove 1 million new line characters from the output, you've only saved 1MB.

You didn't mention any information about the size or anything at all, but if it's big enough to want to fork the project, I'd assume 1MB isn't that much.

Additionally, if you're backing up that much data with this tool, you should probably look into a better solution that backs up the DB in a binary blob, instead of converting it to raw text sql statements.
